[build]
  # Match your Netlify build command
  command = "bun run build"
  # Vite outputs to "dist" by default
  publish = "dist"

  # Allow listing specific client-side env keys to ignore in secret scanning
  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "VITE_PUBLIC_SUPABASE_URL,VITE_PUBLIC_SUPABASE_ANON_KEY"

# SPA routing: send all routes to index.html so React Router can handle them
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


